[project]
name = "Livt.Net"
version = "1.1.0-dev"
path = "src"
outdir = "out"

[tests]
path = "tests"
components = [
	"PacketDataTest",
	"ArpPacketParserTest",
	"ChecksumWordSumTest",
	"ChecksumApiTest",
	"ArpResponderTest",
	"EthernetFrameBuilderTest",
	"EthernetFrameIoTest",
	"EthernetFrameBufferTest",
	"FrameCapacityTest",
	"FrameCompositionTest",
	"EthernetFrameParserTest",
	"IcmpEchoResponderTest",
	"InternetChecksumTest",
	"Ipv4HeaderBuilderTest",
	"Ipv4HeaderChecksumTest",
	"Ipv4PacketParserTest",
	"TcpChecksumTest",
	"TcpConnectionRecognizerTest",
	"TcpHeaderParserTest",
	"TcpSegmentBuilderTest",
	"TcpSynAckFrameComposerTest",
	"CombinatorialForLoopTest"
]

[dependencies]
Livt.IO = "1.2.0-dev"
