[project]
name = "Livt.Net"
version = "0.26.0"
path = "src"
outdir = "out"

[tests]
path = "tests"
components = [
	"ArpPacketParserTest",
	"ChecksumWordSumTest",
	"ArpResponderTest",
	"EthernetFrameBuilderTest",
	"EthernetFrameIoTest",
	"EthernetFrameParserTest",
	"IcmpEchoResponderTest",
	"InternetChecksumTest",
	"Ipv4HeaderBuilderTest",
	"Ipv4HeaderChecksumTest",
	"Ipv4PacketParserTest",
	"TcpChecksumTest",
	"TcpConnectionRecognizerTest",
	"TcpHeaderParserTest",
	"TcpSegmentBuilderTest",
	"TcpSynAckFrameComposerTest",
	"CombinatorialForLoopTest"
]

[dependencies]
Livt.IO = "0.2.0"
