[project]
name = "Livt.Net.GenericPacketsPrototype"
version = "0.1.0"
path = "src"
outdir = "out"

[tests]
path = "tests"
components = ["GenericPacketTest", "PacketMetadataTest"]

[dependencies]
"Livt.Net" = { path = "../.." }
